name: Lint OpenAPI specification

on:
  push:
    branches:
      - main
    paths:
      - 'docs/openapi.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/openapi.yaml'
  workflow_dispatch:

jobs:
  api_lint:
    name: Run API linting
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@2.19.2
  
      - name: Lint API
        run: redocly lint docs/openapi.yaml
